version: "3.8"
services:
#  base_anaconda:
#    build:
#      context: "."
#      dockerfile: "Dockerfile"
#    image: 'base_anaconda'
  web_api4:
    build:
      context: "api_server"
      dockerfile: "Dockerfile"
    networks:
      - main_net
    volumes:
      - .:/home/root/.
    env_file: .env
    image: 'web_api'
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
      - "${API_SSH_PORT}:22"

  web_gui4:
    build:
      context: "gui_server"
      dockerfile: "Dockerfile"
    networks:
      - main_net
    volumes:
      - .:/home/root/.
    env_file: .env
    image: 'web_gui'
    ports:
      - "${BOKEH_PORT}:${BOKEH_PORT}"
      - "${GUI_SSH_PORT}:22"

networks:
  main_net:
