version: "3.8"
services:
  base_anaconda:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: 'base_anaconda'
  web_api2:
    build:
      context: "docker/web_api"
      dockerfile: "Dockerfile"
    env_file: .env
    image: 'web_api'
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
      - "${API_SSH_PORT}:22"

  web_gui2:
    build:
      context: "docker/web_gui"
      dockerfile: "Dockerfile"
    env_file: .env
    image: 'web_gui'
    ports:
      - "${BOKEH_PORT}:${BOKEH_PORT}"
      - "${GUI_SSH_PORT}:22"

