version: "3.8"
services:
  base_anaconda2:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: 'base_anaconda'
  web_api2:
    build:
      context: "docker/web_api"
      dockerfile: "Dockerfile"
    image: 'web_api'
    ports:
      - "8765:8765"
      - "8888:8888"
      - "7777:7777"
      - "6622:22"
  web_gui2:
    build:
      context: "docker/web_gui"
      dockerfile: "Dockerfile"
    image: 'web_gui'
    ports:
      - "6543:6543"
      - "7722:22"
