name: topo2vec
channels:
- pytorch
- conda-forge
- defaults

dependencies:
# Core scientific python
- numpy
- matplotlib
- python=3.6.7
- seaborn
- pip
- scikit-learn
- scikit-image
- pytest
- argparse

# Deep Learning
- pytorch=1.4.0
- torchvision
- cudatoolkit
- ignite  # from the pytorch channel

# Spatial packages
#- rasterstats
- geopy
#- cartopy
- geoalchemy2
- geopandas
#- rasterio
#- contextily
#- pysal
- pyproj
- folium
- gdal
- libgdal
#- kealib
#- geocoder
- geojson
- psycopg2

# Jupyter Environment
- autopep8
- notebook
- ipython
- jupyter_contrib_nbextensions
- jupyter
- nb_conda

# Web app / visualization
- flask
- bokeh
- holoviews

- pip:
    - panel
    - nbclean
    - imageio
    - tqdm
    - auto-tqdm
    - staticmap
    - pathos
    - torchsummary
    - openrouteservice
    - xlrd
    - opencv-python
    - shap
    - future
    - numpy
    - pandas
    - geopandas
    - pytorch-lightning
    - scikit-image
    - sklearn
    - jupyter
    - opencv-python
    - optuna
    - folium