name: topo2vec
channels:
- pytorch
- conda-forge
- defaults

dependencies:
# Core scientific python
- pip

# Web app / visualization
- bokeh

- pip:
    - numpy
    - pandas
    - geopandas
    - pytorch-lightning
    - scikit-image
    - sklearn
    - jupyter
    - folium
    - opencv-python
    - optuna
    - folium
    - geopy
    - flask
    - torchvision
    - bokeh