# define the container itself: all installations etc.
FROM base_anaconda

RUN apt-get update
CMD ["bash", "/home/root/docker/web_api/web_api_startup.sh"]


EXPOSE 8765 6622


#run tensorboard in the right place

#run jupyter notebook in the right place
#CMD python /app/app.py

#run the flask server for getting programers api

#run the bokeh server for using the GUI

#run tests


# run with nvidia-docker (command installed via apt)






